<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Docklonia</RootNamespace>
    <AssemblyName>Docklonia</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Themes\**\*.axaml" />
  </ItemGroup>

</Project>
